### ISSUE TITLE
インストリーム広告を20件取得する際、20件未満だとアプリが落ちる時があります。

### ISSUE THREAD

**Issue by bronzrinji** [mtburn/MTBurn-iOS-SDK-Install-Guide#11]
以下のコードで書いております。

```objective-c
- (void)requestAds
{
    AppDelegate *delegate = (AppDelegate *) [[UIApplication sharedApplication] delegate];
    NSArray *adSpotIdDictForInstream = [delegate adspotIdDict][@"custom_instream"];
   
     [self.instreamAdLoader loadAdWithReturn:adSpotIdDictForInstream[0] adCount:20 positions:@[@0,@1,@2,@3,@4,@5,@6,@7,@8,@9,@10,@11,@12,@13,@14,@15,@16,@17,@18,@19]];
}

- (void)instreamAdLoaderDidFinishLoadingAdWithReturn:(ADVSInstreamAdLoader *)instreamAdLoader
                                  instreamInfoModels:(NSArray*)instreamInfoModels
{
    NSLog(@"instreamAdLoaderDidFinishLoadingAdWithReturn:instreamInfoModels adCount=%d", (int)[instreamInfoModels count]);
        
    instreamlist = [[NSMutableArray alloc]init];   
    //(6) Instrea広告情報を受け取る
    for (ADVSInstreamInfoModel *info in instreamInfoModels) {
               
        NSLog(@" info.position %ld",(long)[info.position integerValue]);

        [instreamlist insertObject:info atIndex:[info.position integerValue]];
        
        
    }
}
```

この時、広告が20件未満の場合、
0件目の広告のinfo.positionが[1]になってしまい、insertできずに落ちてしまいます。

弊社のメディアだけ個別に
強制的にinfo.positionを[0]から始まるようにして頂く、
または、案件重複やダミー案件でも構いませんので20件返して頂くなどのご対応は可能でしょうか？

**Comment by yoheimuta** [comment]
確認いたします。

また、可読性のため、投稿頂いた内容に https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting にあるコードブロックを追記させていただきました。

**Comment by yoheimuta** [comment]
# 現状の仕様について

先に、事前に個別にやり取りさせて頂いていた部分に関して、他の方が把握できるように書きます。

> 0件目の広告のinfo.positionが[1]になってしまい

20 件を要求した際に、19 件など一部の広告案件が取得できない場合は仕様上ありえます

- サーバーとの通信など様々な理由により案件データが不正になっていた、または、そもそも返すべき案件が見つからなかったなど、複数の理由が考えられます

また、一部の広告案件が取得できなかった場合に、その `position（表示位置）` を補正するなどの処理も仕様上していません

- 補正をしていない理由はいくつかありますが、SDK を利用する開発者側で補正する余地があるというのが、現状 SDK 側で補正をしていない理由のひとつです

その上で、`position = 0` であるはずの案件だけが返ってこないという現象があるとしましたら、不具合の可能性が確かにありますが、今のところ弊社側で再現が出来ておりません

- これをうけて、次回バージョンアップ時に、取得した案件データが不正な場合にデバッグログを出力するようにして、再現がしやすいように改修を予定しています

# ワークアラウンドについて

> 弊社のメディアだけ個別に
強制的にinfo.positionを[0]から始まるようにして頂く、
または、案件重複やダミー案件でも構いませんので20件返して頂くなどのご対応は可能でしょうか？

クライアントの更新を伴わない対応案として、事前に個別にやり取りさせて頂いていた部分に関して、補足を交えて書きます。

やり取りさせて頂いていた内容と上記問い合わせに書いてある内容から、`position = 0` の案件が返ってこないことが直接の問題だと考えております。

そのため、管理画面上の`表示位置`を、`0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19` ではなく、すべて `0,0,...0`  にすることで解消する可能性があると思っています。

ただ、クライアントで表示位置を指定した場合はそちらが優先されるので、現在のコードでは管理画面上の表示位置が適用されないと思います。

まずは、お手元の開発環境などで、下記のように変更していただいて問題がないかをご確認いただけますでしょうか？

```objective-c
[self.instreamAdLoader loadAdWithReturn:adSpotIdDictForInstream[0] adCount:20 positions:@[@0,@0,@0,@0,@0,@0, @0,@0,@0,@0,@0,@0,@0,@0,@0,@0,@0,@0,@0,@0]];
```

問題がなさそうでしたら、御社メディアだけ、管理画面上の`表示位置` を優先して適用する修正を行うことで、問題が解消するのではと思っております。

### 実験に使ったコード

```objective-c
    // 提案例
    NSMutableArray *array = [NSMutableArray array];
    [array insertObject:@"0" atIndex:0];
    [array insertObject:@"1" atIndex:0];
    [array insertObject:@"2" atIndex:0];
    [array insertObject:@"3" atIndex:0];
    
    // 現状
    NSMutableArray *array1 = [NSMutableArray array];
    [array1 insertObject:@"0" atIndex:0];
    [array1 insertObject:@"1" atIndex:1];
    [array1 insertObject:@"2" atIndex:2];
    [array1 insertObject:@"3" atIndex:3];
    
    NSLog(@"array: %@", [array description]);
    NSLog(@"array1: %@", [array description]);
```

上記のコードを実行した際のログは次の通りです

```ruby
2015-06-25 10:16:01.971 DemoApp[55715:13177004] array: (
    3,
    2,
    1,
    0
)
2015-06-25 10:16:01.972 DemoApp[55715:13177004] array1: (
    3,
    2,
    1,
    0
)
```

**Comment by yoheimuta** [comment]
@bronzrinji ワークアラウンド案を書きました。ご確認ください。

**Comment by bronzrinji** [comment]
確認しました。
問題なく表示されております！

**Comment by bronzrinji** [comment]
コードを0,0,0,0,,,に書き換えて、
問題なく表示されております。

**Comment by yoheimuta** [comment]
ご確認ありがとうございます。了解しました。

> 問題がなさそうでしたら、御社メディアだけ、管理画面上の表示位置 を優先して適用する修正を行うことで、問題が解消するのではと思っております。

こちらの対応を行いたいと思います。

**Comment by bronzrinji** [comment]
ありがとうございます。
よろしくお願いします。

**Comment by yoheimuta** [comment]
@bronzrinji これからリリースしますので、問題がありましたらお知らせください。

**Comment by bronzrinji** [comment]
ありがとうございます。

**Comment by yoheimuta** [comment]
@bronzrinji リリースしました。よろしくお願いいたします。

**Comment by bronzrinji** [comment]
ありがとうございます。
現在、問題なく稼働しております。

**Comment by yoheimuta** [comment]
ご確認ありがとうございます！

**Comment by yoheimuta** [comment]
@bronzrinji その後問題はありますでしょうか？

問題が解消されていましたら、この issue はクローズしたいと思っております。

**Comment by bronzrinji** [comment]
@yoheimuta 問題ございません。ありがとうございました！

**Comment by yoheimuta** [comment]
@bronzrinji ご確認ありがとうございます！了解しました。

問題は解消したと思われますので、クローズします。
