### ISSUE TITLE
インフィード広告での案件の取得順を固定したい

### ISSUE THREAD

**Issue by sakebook** [mtburn/MTBurn-iOS-SDK-Install-Guide#15]
`loadAdWithReturn`により、複数件取得ができているのですが、取得する度に案件の順番が異なってしまいます。

引数の`positions`と関連付けさせるなど、何か固定順で取得する方法はありますか？

**Comment by yoheimuta** [comment]
確認いたしますmm

**Comment by yoheimuta** [comment]
確認いたしました。

このレポジトリに付属しているデモアプリを使って、次の呼び出しを行いました

- 引数の positions で指定した値が、 広告サーバーから返ってきた 6 件の広告案件それぞれの `position` 属性に割り当てられていることを確認いたしました

```obj-c
// 呼び出し
[self.instreamAdLoader loadAdWithReturn:@"NDgzOjE" adCount:6 positions:@[@7,@14,@21,@28,@35,@42]];
```

```ruby
# サーバーから返ってきた広告案件の print 結果
===DEBUG INFO===

adId: 2144,
...
position: 7, 
===DEBUG INFO===

adId: 17368,
...
position: 14, 
===DEBUG INFO===

adId: 17325,
...
position: 21, 
===DEBUG INFO===

adId: 4818,
...
position: 28, 

===DEBUG INFO===

adId: 6582,
...
position: 35, 
===DEBUG INFO===

 adId: 2147,
...
 position: 42, 
)
```

呼び出し行

- https://github.com/mtburn/MTBurn-iOS-SDK-Install-Guide/blob/master/DemoApp/DemoApp/CustomInstream/ADVSInstreamAppTableViewController.m#L114

ブレークポイントを貼った行

- https://github.com/mtburn/MTBurn-iOS-SDK-Install-Guide/blob/master/DemoApp/DemoApp/CustomInstream/ADVSInstreamAppTableViewController.m#L157 
- ここで `instreamInfoModels` の中身を print してます

> 案件の順番

補足になりますが、ドキュメントにある position（順番）は、[ADVSInstreamInfoModel Class](http://mtburn.github.io/MTBurn-iOS-SDK-Install-Guide/appledoc/2.0.0/html/Classes/ADVSInstreamInfoModel.html#//api/name/position) の position 属性を指しています

-  この点の認識がもし違いましたら、ご確認頂ければと思います

**Comment by sakebook** [comment]
素早い確認ありがとうございます！

> 補足になりますが、ドキュメントにある position（順番）は、ADVSInstreamInfoModel Class の position 属性を指しています

相違ありません。
こちらの説明不足でした。

再度そのメソッドで案件を取得した際も、`position: 7`には、`adId: 2144`の案件が当てはめられるでしょうか？

画面をリフレッシュなどをし、案件を再取得した際に、同じ場所に同じ案件を表示させたいと考えています。

**Comment by yoheimuta** [comment]
補足いただきましてありがとうございます。理解しました。

> 再度そのメソッドで案件を取得した際も、position: 7には、adId: 2144の案件が当てはめられるでしょうか？

あてはめることはできない仕様になっております。

理由についてですが、広告案件のリクエストに対して案件はほぼリアルタイムに計算して、そのアプリに最適な広告案件を返すようにしているためです。

- キャッシュ相当のことをした場合、それができなくなります
- その場合、パフォーマンスが悪化するだけでなく、停止している広告案件が表示されてしまって、クリック時に無効なページやアプリに遷移することも考えられます
 - つまり、媒体の収益性とユーザー体験を損ねるおそれがあります

もし、短時間のキャッシュとして検討頂いている場合は、SDK ではなくアプリ側で実装していただくのが良いのではと考えております。

よろしくお願いいたします。

**Comment by sakebook** [comment]
* 常に最適な案件
 * 無効でない案件

これらを担保するために取得の度に変更する旨承知しました。

踏まえて質問と要望があります。

 * 質問

もしもアプリ側での短時間のキャッシュを実装するとしたら、それは御社としては推奨しない使い方ということになるのでしょうか？
もし再取得を行わないようにした場合、許容される時間などはありますか？

 * 要望

debugで出力されている`adId `をカスタムインフィード広告のパラメータに追加できないでしょうか？
案件をユニークにする値に利用できないかと考えています。

---

以上、よろしくお願いします。

**Comment by yoheimuta** [comment]
了解しました。
質問と要望を、確認させていただきます。

よろしくお願いいたします。

**Comment by yoheimuta** [comment]
確認いたしました。

> もしもアプリ側での短時間のキャッシュを実装するとしたら、それは御社としては推奨しない使い方ということになるのでしょうか？

推奨しない使い方になります。
理由は https://github.com/mtburn/MTBurn-iOS-SDK-Install-Guide/issues/15#issuecomment-120287044 に書いた通り、ネガティブな影響が考えられるためです。

> もし再取得を行わないようにした場合、許容される時間などはありますか？

1 ~ 2 分程度は許容されます。

> debugで出力されているadIdをカスタムインフィード広告のパラメータに追加できないでしょうか？

弊社側で高いパフォーマンスをアプリ開発者様に提供することを妨げることにつながると判断しましたので、追加することはできません。

よろしくお願いいたします。

**Comment by sakebook** [comment]
確認ありがとうございます。

 * 1~2分は許容するが推奨しない
 * `adId`パラメータの追加の負荷

承知しました。

**Comment by yoheimuta** [comment]
よろしくお願いいたします。

**Comment by yoheimuta** [comment]
@sakebook こちらの issue はクローズ可能でしょうか？ご確認頂ければと思いますmm

**Comment by sakebook** [comment]
中途半端な状態になっていました。申し訳ありません。

固定にできない仕様とその理由を把握しましたので、クローズして問題ありません。
確認と対応ありがとうございます。

**Comment by yoheimuta** [comment]
ご確認ありがとうございます！クローズします。
