### ISSUE TITLE
カオコレ｜テキスト広告が表示されない

### ISSUE THREAD

**Issue by bsnewbiz** [mtburn/MTBurn-iOS-SDK-Install-Guide#16]
- アプリ情報：
▪︎アプリ名：カオコレ
▪︎広告id: OTE2OjIyNjk
▪︎media id：823
- いつから:  ８月実装以来ずっと表示されなかった
- どの広告種別で: テキストのみ広告
- 症状: エラー1000になって、広告データがなさそう
- 再現条件: デモアプリ・カオコレプログラム中で普通にリクエストする
- 再現した際のログ/プロジェクトファイル(あれば):
![default](https://cloud.githubusercontent.com/assets/13780100/9268523/efbe5e02-429a-11e5-892f-56b1c825be9f.png)
![appdelelgate](https://cloud.githubusercontent.com/assets/13780100/9268567/70008144-429b-11e5-9c22-50e7f1645a4d.png)
![class](https://cloud.githubusercontent.com/assets/13780100/9268568/700844f6-429b-11e5-8ce7-6821e0499b91.png)
- 備考:テストIDと昔使ったテキスト広告のIDを使って全部正常に表示される。カオコレのIDだけ表示されない。

**Comment by yoheimuta** [comment]
お手数おかけします。確認します。

**Comment by yoheimuta** [comment]
@bsnewbiz 確認しました。

弊社側のサーバーサイドの不具合の可能性が高いと思われます。
影響範囲が広いため、安全のため週明けに修正したものをリリースする予定です。

リリースしましたら、こちらにコメントを書いてお知らせします。
お手数おかけしますが、よろしくお願いします。

**Comment by bsnewbiz** [comment]
承知しました。
引き続きよろしくお願いします。

**Comment by yoheimuta** [comment]
@bsnewbiz お手数おかけしております。

修正をリリースしました。

問題が解消しているかご確認ください。
よろしくお願いします。

**Comment by bsnewbiz** [comment]
お疲れ様です。
広告の表示は確認できました。
問題なさそうです。

ありがとうございます。

**Comment by yoheimuta** [comment]
ご確認ありがとうございます。
表題の件が解消されたとのことですので、この issue をクローズさせていただきます。
お手数おかけしました。
