### ISSUE TITLE
デモアプリ（iOS）のインフィード広告の取得が失敗する。

### ISSUE THREAD

**Issue by SunaSuna** [mtburn/MTBurn-iOS-SDK-Install-Guide#20]
本日sdk(2.1.0)をダウンロードさせていただき、動作チェックを行いましたが
ADVSInstreamAppTableViewController.mのrequestAdsがコールされたあと、添付のようにエラーとなります。
<img width="930" alt="2016-03-07 16 09 24" src="https://cloud.githubusercontent.com/assets/3054900/13562744/02390cc2-e47f-11e5-8aa0-0b859d4a1e00.png">

デフォルト設定からいじっていないので、テストアカウントで動いているはずなのですが。。。。。
こちら何か情報等ございますでしょうか？
よろしくお願いいたします。

[ 動作確認環境 ]
OS X 10.11
Xcode 7.2
iOS9.2

**Comment by yoheimuta** [comment]
お手数おかけします。確認致します。

**Comment by SunaSuna** [comment]
よろしくお願いいたします。

**Comment by yoheimuta** [comment]
テスト用の広告の配信がされておりませんでした。
現在は配信されているかと思いますので、あらためてご確認頂けますでしょうか？

よろしくお願い致します。

**Comment by SunaSuna** [comment]
取得できているのが確認できました。
迅速なご対応ありがとうございます。

**Comment by yoheimuta** [comment]
ご確認ありがとうございます。
お手数をおかけしました。
