### ISSUE TITLE
BitCode対応について

### ISSUE THREAD

**Issue by toyship** [mtburn/MTBurn-iOS-SDK-Install-Guide#21]
恐れいりますが、Bitcode対応についてご確認いただけませんでしょうか。

下記の環境でサンプルプロジェクトを作成し、インストール手順通りに Build Settings で```Enable BitCode=YES``` としてビルドを行うと、Bitcode非対応であるとのエラーが表示されてしまいます。
（2.1.0のリリースノートをみると、Bitcode対応のように見えますが……）

* Xcode Version 7.2.1 (7C1002)
* Sample Project Language: Swift
* MTBurn Version 2.1.0

Error Messge

````
ld: bitcode bundle could not be generated because '/Users/TachibanaKaoru/Desktop/bitcodetest/bitcodetest/AppDavis.framework/AppDavis(ADVSInstreamAdCellManager.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
````

**Comment by yoheimuta** [comment]
お手数おかけします。確認致します。

**Comment by yoheimuta** [comment]
@toyship 次の三通りを試してみましたが、こちらで再現が出来ておりません

- 下記、それぞれ https://github.com/mtburn/MTBurn-iOS-SDK-Install-Guide/releases/tag/v2.1.0 から zip を DL して使ってます（以下、v2.1.0 ディレクトリ）
- それぞれのフレームワーク利用側プロジェクトにて、`ENABLE_BITCODE=YES` を確認
- Xcode は Version 7.2.1 (7C1002) にそろえています

1) `v2.1.0 ディレクトリ` に含まれる、`DemoApp` にて、 `v2.1.0 ディレクトリ` に含まれる `AppDavis.framework` を組み込んでビルドする

2) `v2.1.0 ディレクトリ` に含まれる、`DemoAppSwift` にて、 `v2.1.0 ディレクトリ` に含まれる `AppDavis.framework` を組み込んでビルドする

3) 0 から Simple View のアプリ（Swift）をつくって、 `v2.1.0 ディレクトリ` に含まれる `AppDavis.framework` を組み込んでビルドする

上記の再現手順に不足あれば、ご指摘をお願いします。
または、再現手順や再現できるプロジェクトファイル（の zip など）を提供頂けますと幸いです。

お手数をおかけしますが、ご確認をお願い致します。

**Comment by toyship** [comment]
ご確認ありがとうございました。

こちらでもほぼ同じ状況で試しておりますが、ちょっと手順が違います。
プロジェクトにフレームワークをリンクするだけではなく、AppDavis側の機能をよぶことで実際にリンクされ、エラーが表示されるようになると思います。

たとえば、3) の状況プロジェクトの```application:didFinishLaunchingWithOptions``` などでAppDavisの機能をよんでご確認いただけますでしょうか。

（例）
```
        AppDavis.initMedia("12345")
        adLoader = ADVSInstreamAdLoader()
```

**Comment by yoheimuta** [comment]
@toyship ご確認ありがとうございます。

> たとえば、3) の状況プロジェクトのapplication:didFinishLaunchingWithOptions などでAppDavisの機能をよんでご確認いただけますでしょうか。

こちらを試してみましたが、再現できませんでした。

https://github.com/mtburn/MTBurn-iOS-SDK-Install-Guide/compare/shared-sample-proj/21 にこちらで試した際のプロジェクトファイルを含めてみましたので、ご確認いただけますでしょうか？

- 起動直後にファーストビューでインターステイシャル広告を表示するようにしています

![image](https://cloud.githubusercontent.com/assets/1223268/13866722/bfd5e546-ecfb-11e5-9195-1fe9af24b563.png)

**Comment by toyship** [comment]
サンプル作成ありがとうございます！
3211_sampleのソースコードで確認させていただきました。

通常にビルドした場合、およびシミュレーターでの動作には問題ないんですが、ビルドデバイスを ```Generic iOS Device``` に選んで ```Product``` メニューの ```Archive``` コマンドを実行すると下記のエラーが発生しています。

````
ld: bitcode bundle could not be generated because '/Users/TachibanaKaoru/Downloads/MTBurn-iOS-SDK-Install-Guide-shared-sample-proj-21/3211_sample/AppDavis.framework/AppDavis(ADVSInstreamAdCellManager.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
````

**Comment by yoheimuta** [comment]
@toyship こちらでも再現しました！
修正致します。お手数をおかけします。

**Comment by toyship** [comment]
確認ありがとうございます。
特にいそいでいるということではありませんので、次回リリースの際に修正いただければと思います。
よろしくお願いします。

**Comment by yoheimuta** [comment]
@toyship 

> 特にいそいでいるということではありませんので、次回リリースの際に修正いただければと思います。

状況の共有助かります。

了解致しました。よろしくお願い致します。

**Comment by yoheimuta** [comment]
@toyship 修正を行った [v2.1.1](https://github.com/mtburn/MTBurn-iOS-SDK-Install-Guide/releases/tag/v2.1.1) をリリースしました。

問題がないかご確認をお願い致します。

**Comment by toyship** [comment]
返信が遅れてしまって申し訳ありません。
2.1.1で確認し、BitCode対応対応させていることを確認させていただきました。

ご対応ありがとうございました。

**Comment by yoheimuta** [comment]
ご確認ありがとうございます！

それでは、クローズさせていただきます。
