### ISSUE TITLE
AppDavisでprivate APIが使用されている可能性がある。（リジェクト対象となります）

### ISSUE THREAD

**Issue by yuki-takano** [mtburn/MTBurn-iOS-SDK-Install-Guide#24]
お世話になっております。

先日App Storeにアプリを申請した際、以下の理由でリジェクトを受けました。
アプリのバイナリを調べてみるとADVSInstreamAdLoaderで該当のメソッドが
使用されているようでした。
ver2.1.1は最新かと思いますが、今後private apiを使用しないバージョンを
リリースする予定はございますか？

``````````````` リジェクト理由``````````````
Performance - 2.5.1

Your app uses or references the following non-public APIs:

: loadAd:

The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.

`````````````リジェクト理由``````````````

よろしくお願いします。
```````````````

**Comment by yoheimuta** [comment]
ご連絡ありがとうございます。

> ver2.1.1は最新かと思いますが、今後private apiを使用しないバージョンを
リリースする予定はございますか？

こちら確認致します。

**Comment by yoheimuta** [comment]
> アプリのバイナリを調べてみるとADVSInstreamAdLoaderで該当のメソッドが
使用されているようでした。

ここでいう該当のメソッドとは、 Apple からの文面と合わせて考えると、 `loadAd:` メソッド自体のことを指している認識でしょうか？

ADVSInstreamAdLoader で宣言されている `loadAd:` メソッド自体は http://mtburn.github.io/MTBurn-iOS-SDK-Install-Guide/appledoc/latest/Classes/ADVSInstreamAdLoader.html#//api/name/loadAd にある通り、HIKE が配信する広告を読み込むためのメソッドです。

[Private APIと同じ名前のメソッドについてのAppleの審査問題](http://sonson.jp/blog/2010/09/23/private-api/) で書かれている、アップルのprivate APIと衝突していることを理由としたリジェクトに読めましたが、いかがでしょうか？

もしそうであれば、まずは Apple への回答方法として、変更は難しいことを伝えて交渉して頂く方法もありそうだと考えてます。

> ver2.1.1は最新かと思いますが、今後private apiを使用しないバージョンを
リリースする予定はございますか？

`loadAd:` メソッドは公開されているメソッドのため、変更すると互換性がなくなります。
そのため、直近そういった互換性をなくすような大きなバージョンアップのリリースは予定していません（補足: あくまでも、現時点での予定です）。

**Comment by yoheimuta** [comment]
@yuki-takano お手数をおかけしています。
https://github.com/mtburn/MTBurn-iOS-SDK-Install-Guide/issues/24#issuecomment-244706142 に確認内容をまとめましたので、ご確認をお願い致します。

**Comment by yuki-takano** [comment]
ご回答頂き、ありがとうございます。
アップルのprivate APIと衝突していることを理由としたリジェクトで間違いなさそうです。
私の説明に誤植があり、申し訳ございませんでした。
変更が難しいことを伝えて、交渉しようと思います。

ありがとうございました。

**Comment by yoheimuta** [comment]
ご確認いただきありがとうございます。

> 変更が難しいことを伝えて、交渉しようと思います。

承知致しました。よろしくお願い致します。

**Comment by yuki-takano** [comment]
お世話になっております。
Appleに交渉したのですが、APIの名前を変えるよう言われ、再リジェクトされてしまいました。
恐らくAppleの担当者によって対応が変わるのだと思います。
SDK側のAPIの名前を変えることはやはり厳しいですかね？
難しいことを要求しているとしたら、申し訳ありません。

**Comment by yoheimuta** [comment]
ご連絡いただきありがとうございます。

> 恐らくAppleの担当者によって対応が変わるのだと思います。

弊社でも issue 表題の理由でリジェクトされたという報告ははじめてですので、おそらく担当者起因がありそうだとは思いました。

即答は難しい内容ですので、検討させてください。
お手数をおかけしますが、よろしくお願い致します。

**Comment by yuki-takano** [comment]
承知いたしました。
よろしくお願いいたします。

**Comment by yoheimuta** [comment]
@yuki-takano 検討致しました。
SDK を利用して頂いている他社様の申請状況と要望を調査した上で対応を決めることになりました。そのため、すぐの対応は難しいです。

当面のワークアラウンドとしては、 https://github.com/mtburn/MTBurn-JavaScript-SDK-Install-Guide のご利用を案内させていただくことになりました。
こちらは WebView を使って実装していただくスタイルになります。

お手数ですが、ご確認をお願い致します。

**Comment by yuki-takano** [comment]
承知いたしました。
よろしくお願いいたします。

**Comment by yoheimuta** [comment]
@yuki-takano お手数をお掛けしています。

さきほど、この issue 表題を解消した [v3.0.0](https://github.com/mtburn/MTBurn-iOS-SDK-Install-Guide/releases/tag/v3.0.0) をリリースしました。
ご確認の程、よろしくお願いします。

**Comment by yuki-takano** [comment]
ご対応いただき、誠にありがとうございます。
大変助かります。

よろしくお願いします。
