### ISSUE TITLE
ADVSInstreamInfoModelに、iconImageとmainImageのプロパティ追加依頼

### ISSUE THREAD

**Issue by mogmet** [mtburn/MTBurn-iOS-SDK-Install-Guide#6]
お世話になっております。

カスタムインフィード広告の画像を取得する際に、loadIconImageもしくはloadImageを使って取得する仕様になっておりますが、
画像キャッシュなど、こちらで制御したい部分もあるので画像取得は直接NSURLなどのプロパティとして取得するようにすることはできないでしょうか。

よろしくお願いします。

**Comment by yoheimuta** [comment]
ご意見ありがとうございます。

Android SDK では同様の要望をもとにプロパティとして取得できるようにした経緯がありますので、iOS SDK についても同様の対応をしたいと思います。

優先度を調整したいと思いますので、SDK を組み込む際のブロッカーになっている状況かを教えて頂けますでしょうか？

よろしくお願いします。

**Comment by mogmet** [comment]
広告SDKの共通の処理として作っているので、画像だけ表示できない状況になっています。
一旦は画像なしで実装を進めていきますが、なるべく早めに実装いただけると幸いです。

よろしくお願いします。

**Comment by yoheimuta** [comment]
了解しました。優先度高めで対応します。

**Comment by mogmet** [comment]
お手数おかけいたします。何卒よろしくお願いします。

**Comment by yoheimuta** [comment]
https://github.com/mtburn/MTBurn-iOS-SDK-Install-Guide/releases/tag/v1.2.0 にて、バージョンアップした SDK を公開しました。

ご確認お願いします。

**Comment by yoheimuta** [comment]
@mogmet こちらはクローズしても大丈夫でしょうか。

**Comment by yoheimuta** [comment]
いったんクローズさせていただきます。問題がありましたら、Reopen ください。
