### ISSUE TITLE
デモアプリへのリンクが切れています｡

### ISSUE THREAD

**Issue by u16suzu** [mtburn/MTBurn-iOS-SDK-Install-Guide#7]
お疲れ様です｡
以下のQA ページ内にあるデモアプリへのリンクが切れています｡

https://github.com/mtburn/MTBurn-iOS-SDK-Install-Guide/blob/master/QA.md#サンプルプロジェクトはありますか

**Comment by yoheimuta** [comment]
ご報告ありがとうございます！

https://github.com/mtburn/MTBurn-iOS-SDK-Install-Guide/commit/d0eb54fabc5f332111fac9872335e37f8699d4cc にて修正しました。

**Comment by u16suzu** [comment]
素早い対応､ありがとうございます!
無事リンクが踏めることを確認いたしましたのでクローズさせて頂きます｡
