### ISSUE TITLE
ADVSInterstitialLoaderDelegateに閉じるボタンクリックした際のdelegateを追加実装して欲しいです

### ISSUE THREAD

**Issue by hanana0501** [mtburn/MTBurn-iOS-SDK-Install-Guide#8]
鈴木さんを通じて一度問い合わせしました件です。
cocos2d-x ver3.5 iOS7.0~にてinterstitialを表示しているにも関わらず、背後にあるcocosのオブジェクトのタッチすることできてしまうという現象が発生しています。
こちらの調査をまず依頼したいです。

また鈴木さんより再現プロジェクトを頂けると捗るというお話も頂戴しておりますが、
申し訳ありませんがただいまリリース前にて時間がとれず、再現プロジェクトを作ることが不可能です。
なので当座の応急処置となりますが、私の方にてinterstitial表示時にcocosのviewのタップイベントを封じます。そして広告タップ時or閉じるボタンタップ時にタップイベント封印を解除します。
上記の実装しますのでSDK側の方にて閉じるボタンのdelegate実装をお願いしたいです。

なお、こちらの事情で大変申し訳ないのですが、リリースの日付が迫っており、6/12（金）までにdelegate実装不可能な見込みであるならばプランBをとりますのでお伝えいただけますでしょうか。
よろしくお願いいたします。

**Comment by yoheimuta** [comment]
了解しました。確認します。

**Comment by yoheimuta** [comment]
確認しました。

> 6/12（金）までにdelegate実装不可能な見込みであるならばプランBをとりますのでお伝えいただけますでしょうか

6/12（金）までにdelegate実装可能な見込みです。

> cocos2d-x ver3.5 iOS7.0~にてinterstitialを表示しているにも関わらず、背後にあるcocosのオブジェクトのタッチすることできてしまうという現象が発生しています。
こちらの調査をまず依頼したいです。

現在の調査状況としましては、弊社のデモアプリでは再現しておりません。

引き続き調査するのと合わせて、現在は透明なビューを背後においてタッチできないようにしているところを、薄い黒などの色をつけられるようにすることを検討したいと思います。

問題が起きたときの原因が特定しやすくなるだろうというのが理由のひとつです

よろしくお願いします。

**Comment by yoheimuta** [comment]
[v1.3.0](https://github.com/mtburn/MTBurn-iOS-SDK-Install-Guide/releases/tag/v1.3.0) をリリースしました。

- API は[こちら](http://mtburn.github.io/MTBurn-iOS-SDK-Install-Guide/appledoc/latest/Protocols/ADVSInterstitialAdLoaderDelegate.html#//api/name/interstitialAdLoaderDidCloseIntersititialAdView:) を参照ください。

よろしくお願いいたします。

**Comment by hanana0501** [comment]
実装ありがとうございます！取り急ぎお礼まで。。

**Comment by hanana0501** [comment]
@yoheimuta 
先ほどこちらで実装いたしまして無事背後のタップイベントをとらない仕様にできました！
ご対応いただき誠にありがとうございました
