### ISSUE TITLE
【ver1.3.0】インタースティシャル広告のskipが行われていない

### ISSUE THREAD

**Issue by hanana0501** [mtburn/MTBurn-iOS-SDK-Install-Guide#9]
issue連投すみません。
ver1.3.0にあげて実装したところ、管理画面側では5回に1回のインタースティシャル広告表示設定にしているのですが、loadRequestするとinterstitialAdLoaderDidSkipLoadingAdのdelegateメソッドが呼ばれずに毎回広告が表示されてしまうという現象にみまわれております。
ご対応をよろしくお願いいたします。

**Comment by yoheimuta** [comment]
お手数おかけします。確認致します。

**Comment by yoheimuta** [comment]
> 管理画面側では5回に1回のインタースティシャル広告表示設定にしている

設定を確認したいので、media_id（メディア ID） と adspot_id（枠 ID）を共有して頂いても良いでしょうか？

**Comment by yoheimuta** [comment]
また、以前のバージョンではできていましたでしょうか？調査の参考にさせて頂ければと思います。

**Comment by yoheimuta** [comment]
まず、クライアント側の調査をしました。

デモアプリで動作確認をしました。

- 最初の表示までは 2 回スキップして、その後は 1 回スキップすることを確認しました
- コード差分は [Added demo code for confirming to skip insterstitial ads by yoheimuta · Pull Request #10 · mtburn/MTBurn-iOS-SDK-Install-Guide](https://github.com/mtburn/MTBurn-iOS-SDK-Install-Guide/pull/10) をご確認ください

![20150617_interstitial_demo](https://cloud.githubusercontent.com/assets/1223268/8199636/c0a1bda0-14f3-11e5-9ccf-e6492e2ec01f.gif)

上記から、インターステイシャル広告のスキップ機能が v1.3.0 でリグレッションしていることは確認できませんでした。

よろしくお願いします。

**Comment by hanana0501** [comment]
ご返信ありがとうございます。
再確認したところadspot_idのコピペミスによって、スキップがされずに毎回表示…となっていた模様です。
本当に申し訳ない＆お手数をおかけしてすみません。丁寧にありがとうございました！
closeさせていただきます。。

**Comment by yoheimuta** [comment]
ご確認ありがとうございます！

了解致しました。
